# Generated by Django 2.0.3 on 2018-03-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazioni', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='panino',
            name='disponibilita',
            field=models.DateTimeField(null=True, verbose_name='giorno disponibilità'),
        ),
        migrations.AddField(
            model_name='panino',
            name='inserimento',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='giorno inserimento'),
        ),
    ]
